mysource <- function() {

#     require(baseline)
#     require(datasets)  #default
     require(digest)
#     require(FME)
#     require(graphics)  #default
#     require(grDevices) #default
     require(grid)      
#     require(lattice)
     require(latticeExtra)
     require(memoise)
#     require(methods)   #default
     require(minpack.lm)
     require(NORMT3)
#     require(signal)
#     require(sm)
     require(SparseM)
#     require(stats)     #default
#     require(utils)     #default
#     require(wavelets)

     require(tcltk)     #default
     require(tkrplot)
     require(gWidgets2)
     require(gWidgets2tcltk)
     options(guiToolkit="tcltk")

     source('~/mydir/LAVORI/R/RxpsG-2.2/R/RXPSGUI.r', encoding='UTF-8')
     source('~/mydir/LAVORI/R/RxpsG-2.2/R/XPSAddFitComponent.r', encoding='UTF-8')
     source('~/mydir/LAVORI/R/RxpsG-2.2/R/XPSAnnotateGUI.r', encoding='UTF-8')
     source('~/mydir/LAVORI/R/RxpsG-2.2/R/XPSClass.r', encoding='UTF-8')
     source('~/mydir/LAVORI/R/RxpsG-2.2/R/XPSConstrain.r', encoding='UTF-8')
     source('~/mydir/LAVORI/R/RxpsG-2.2/R/XPSConstraintsGUI.r', encoding='UTF-8')
     source('~/mydir/LAVORI/R/RxpsG-2.2/R/XPSCoreLineList.r', encoding='UTF-8')
     source('~/mydir/LAVORI/R/RxpsG-2.2/R/XPSCustomBaseline.r', encoding='UTF-8')
     source('~/mydir/LAVORI/R/RxpsG-2.2/R/XPSCustomPlotGUI.r', encoding='UTF-8')
     source('~/mydir/LAVORI/R/RxpsG-2.2/R/XPSDiffGUI.r', encoding='UTF-8')     
     source('~/mydir/LAVORI/R/RxpsG-2.2/R/XPSElements.r', encoding='UTF-8')
     source('~/mydir/LAVORI/R/RxpsG-2.2/R/XPSElemTabGUI.r', encoding='UTF-8')
     source('~/mydir/LAVORI/R/RxpsG-2.2/R/XPSEshiftGUI.r', encoding='UTF-8')
     source('~/mydir/LAVORI/R/RxpsG-2.2/R/XPSExportAsciiGUI.r', encoding='UTF-8')
     source('~/mydir/LAVORI/R/RxpsG-2.2/R/XPSExtractGUI.r', encoding='UTF-8')
     source('~/mydir/LAVORI/R/RxpsG-2.2/R/XPSFilterGUI.r', encoding='UTF-8')
     source('~/mydir/LAVORI/R/RxpsG-2.2/R/XPSFitAlgorithms.r', encoding='UTF-8')
     source('~/mydir/LAVORI/R/RxpsG-2.2/R/XPSFitCompClass.r', encoding='UTF-8')
     source('~/mydir/LAVORI/R/RxpsG-2.2/R/XPSFitInfoGUI.r', encoding='UTF-8')
     source('~/mydir/LAVORI/R/RxpsG-2.2/R/XPSFitLM.r', encoding='UTF-8')
     source('~/mydir/LAVORI/R/RxpsG-2.2/R/XPSFitParamInfoGUI.r', encoding='UTF-8')
     source('~/mydir/LAVORI/R/RxpsG-2.2/R/XPSFNameList.r', encoding='UTF-8')
     source('~/mydir/LAVORI/R/RxpsG-2.2/R/XPSGetHvalue.r', encoding='UTF-8')
     source('~/mydir/LAVORI/R/RxpsG-2.2/R/XPSImportAsciiGUI.r', encoding='UTF-8')
     source('~/mydir/LAVORI/R/RxpsG-2.2/R/XPSLatticeAnnotateGUI.r', encoding='UTF-8')
     source('~/mydir/LAVORI/R/RxpsG-2.2/R/XPSModFitGUI.r', encoding='UTF-8')
     source('~/mydir/LAVORI/R/RxpsG-2.2/R/XPSMoveBaseLineGUI.r', encoding='UTF-8')
     source('~/mydir/LAVORI/R/RxpsG-2.2/R/XPSMoveCompGUI.r', encoding='UTF-8')
     source('~/mydir/LAVORI/R/RxpsG-2.2/R/XPSnlsLM.r', encoding='UTF-8')
     source('~/mydir/LAVORI/R/RxpsG-2.2/R/XPSOverlayEngine.r', encoding='UTF-8')
     source('~/mydir/LAVORI/R/RxpsG-2.2/R/XPSOverlayGUI.r', encoding='UTF-8')
     source('~/mydir/LAVORI/R/RxpsG-2.2/R/XPSPreferencesGUI.r', encoding='UTF-8')
     source('~/mydir/LAVORI/R/RxpsG-2.2/R/XPSProcess.r', encoding='UTF-8')
     source('~/mydir/LAVORI/R/RxpsG-2.2/R/XPSProcessCoreLineGUI.r', encoding='UTF-8')
     source('~/mydir/LAVORI/R/RxpsG-2.2/R/XPSQuantifyGUI.r', encoding='UTF-8')
     source('~/mydir/LAVORI/R/RxpsG-2.2/R/XPSRead.r', encoding='UTF-8')
     source('~/mydir/LAVORI/R/RxpsG-2.2/R/XPSRead.scienta.r', encoding='UTF-8')
     source('~/mydir/LAVORI/R/RxpsG-2.2/R/XPSRead.vamas.r', encoding='UTF-8')
     source('~/mydir/LAVORI/R/RxpsG-2.2/R/XPSRead.Genplot.r', encoding='UTF-8')
     source('~/mydir/LAVORI/R/RxpsG-2.2/R/XPSReportGUI.r', encoding='UTF-8')
     source('~/mydir/LAVORI/R/RxpsG-2.2/R/XPSResetAnalysisGUI.r', encoding='UTF-8')
     source('~/mydir/LAVORI/R/RxpsG-2.2/R/XPSSampleInfoGUI.r', encoding='UTF-8')
     source('~/mydir/LAVORI/R/RxpsG-2.2/R/XPSSaveDataGUI.r', encoding='UTF-8')
     source('~/mydir/LAVORI/R/RxpsG-2.2/R/XPSSaveRetrieveBkp.r', encoding='UTF-8')
     source('~/mydir/LAVORI/R/RxpsG-2.2/R/XPSSetCoreLineGUI.r', encoding='UTF-8')
     source('~/mydir/LAVORI/R/RxpsG-2.2/R/XPSSetGraphDevGUI.r', encoding='UTF-8')
     source('~/mydir/LAVORI/R/RxpsG-2.2/R/XPSSetFNameCLineGUI.r', encoding='UTF-8')
     source('~/mydir/LAVORI/R/RxpsG-2.2/R/XPSSetWinSizeGUI.r', encoding='UTF-8')
     source('~/mydir/LAVORI/R/RxpsG-2.2/R/XPSSetWDGUI.r', encoding='UTF-8')
     source('~/mydir/LAVORI/R/RxpsG-2.2/R/XPSSpectList.r', encoding='UTF-8')
     source('~/mydir/LAVORI/R/RxpsG-2.2/R/XPSSpectNameChangeGUI.r', encoding='UTF-8')
     source('~/mydir/LAVORI/R/RxpsG-2.2/R/XPSSplitGUI.r', encoding='UTF-8')
     source('~/mydir/LAVORI/R/RxpsG-2.2/R/XPSSprucingGUI.r', encoding='UTF-8')
     source('~/mydir/LAVORI/R/RxpsG-2.2/R/XPSSurElmtIdentifyGUI.r', encoding='UTF-8')
     source('~/mydir/LAVORI/R/RxpsG-2.2/R/XPSSurveyUtilities.r', encoding='UTF-8')
     source('~/mydir/LAVORI/R/RxpsG-2.2/R/XPSSwitchBE.KE.GUI.r', encoding='UTF-8')
     source('~/mydir/LAVORI/R/RxpsG-2.2/R/XPSTwoScalePlotGUI.r', encoding='UTF-8')
     source('~/mydir/LAVORI/R/RxpsG-2.2/R/XPSUtilities.r', encoding='UTF-8')
     source('~/mydir/LAVORI/R/RxpsG-2.2/R/XPSVBTopGUI.r', encoding='UTF-8')
     source('~/mydir/LAVORI/R/RxpsG-2.2/R/XPSVmsCorrGUI.r', encoding='UTF-8')
     source('~/mydir/LAVORI/R/RxpsG-2.2/R/XPSZoomCurGUI.r', encoding='UTF-8')

     setwd("~/mydir/LAVORI/R/Analysis/")
     
}
